### ISSUE TITLE
Сделать вариант дропдауна с радио-кнопками

### ISSUE THREAD

**Issue by webmayak** [AileenKingsler/dropdown#1]
Аналогично как сейчас чекбоксы, но только радио-кнопками:
![image](https://user-images.githubusercontent.com/642519/76695354-00bc7880-66ca-11ea-97da-63ba4588bd8a.png)

**Comment by AileenKingsler** [comment]
Сделала https://github.com/AileenKingsler/dropdown/commit/a459caae29bac4d62507b87b378fb051d9befc20
![Dropdown - Google Chrome](https://user-images.githubusercontent.com/44943008/76696608-12594c80-66d9-11ea-887f-e527bc8aeb77.jpg)
