### ISSUE TITLE
Сделать вариант дропдауна с кнопкой сабмита

### ISSUE THREAD

**Issue by webmayak** [AileenKingsler/dropdown#2]
Вот как тут, чтобы была кнопка отправки формы:
![image](https://user-images.githubusercontent.com/642519/76695361-395c5200-66ca-11ea-97a0-e0308ee36d80.png)

**Comment by AileenKingsler** [comment]
Сделала https://github.com/AileenKingsler/dropdown/commit/cf72b4f057f2d100173582dba2008d5002f16715
![Dropdown - Google Chrome](https://user-images.githubusercontent.com/44943008/76696630-492f6280-66d9-11ea-953b-fb0cc26d5726.jpg)
