### ISSUE TITLE
Сделать вариант дропдауна с заголовком, аналогично как у панелей

### ISSUE THREAD

**Issue by webmayak** [AileenKingsler/dropdown#3]
Перед списком опций необходим заголовок, чтобы было понятно что это такое:
![image](https://user-images.githubusercontent.com/642519/76698292-f5c70f80-66ec-11ea-961a-93871d5a1ac7.png)

**Comment by AileenKingsler** [comment]
Сделала https://github.com/AileenKingsler/dropdown/commit/d22aabac0a5d8670fd19b15b2fc5e5418b809786
![Dropdown - Google Chrome](https://user-images.githubusercontent.com/44943008/76756110-dacdcb80-67d0-11ea-81f4-f69fedf2caea.jpg)
