### ISSUE TITLE
Сделать форк для Bootstrap 3

### ISSUE THREAD

**Issue by webmayak** [AileenKingsler/dropdown#4]
М? Насколько это может быть трудозатратно? Просто основное куда бы это могло сейчас пойти - это ЛК менеджера для maxcommerce, а там пока что Bootstrap 3.. 😒

![image](https://user-images.githubusercontent.com/642519/76698374-cb298680-66ed-11ea-905c-ea653259e2f8.png)

**Comment by AileenKingsler** [comment]
@webmayak Вполне реально, я думаю, в Bootstrap 3 тоже есть дропдауны, насколько я помню

**Comment by webmayak** [comment]
они там точно есть)

![image](https://user-images.githubusercontent.com/642519/76703259-2ecaa880-671c-11ea-8a58-4a904db085db.png)

**Comment by AileenKingsler** [comment]
Сделала https://github.com/AileenKingsler/dropdown/commit/8c97229426e6958f5c13b0ae9e01f0cf6286be1a
![Dropdown - Google Chrome](https://user-images.githubusercontent.com/44943008/76764811-36a05080-67e1-11ea-8d06-7fe7baf11f15.jpg)
![Dropdown - Google Chrome 2](https://user-images.githubusercontent.com/44943008/76764820-3acc6e00-67e1-11ea-85e3-2f5cfb677e2b.jpg)
